heat_template_version: 2015-04-30

description: Template for deploying 1xCLA

parameters:

  lapf_identifier:
    description: Cluster identification
    type: number
    constraints:
      - range: { min: 1, max: 65535 }
        description: (lapf_identifier must be number <1-65535>)

  lapf_tenant_name:
    type: string
    description: Name of LA tenant 
    default: LATenant 
 
  image_name:
    type: string
    description: Name of LA platform image

  flavor_name:
    type: string
    description: Flavor name
    default: dummyApp_flavor
  
  network_name:
    description: TTPB net name
    type: string
    default: com.nokia.la.nw.ttb
  
  subnet_name:
    type: string
    description: Subnet name for TTB network
    default: com.nokia.la.nw.ttb_subnet

  port_name:
    type: string
    description: LA Platform TTB network port
    default: com.nokia.la.nw.ttb_port
  
  LAPlatformTTBNetIP:
    type: string
    description: IP for TTB network in LA Platform
    default: 192.168.254.3
 
  app_eth0_ip:
    type: string
    description: IP for App_VM
    default: 192.168.254.13

  app_mask:
    type: string
    description: mask for App_VM
    default: 27

  network_name2:
    description: Management network name
    type: string
    default: com.nokia.la.nw.management

resources:

  LA_Platform_TTB_Net_Port:
    type: OS::Neutron::Port
    properties:
      name: { get_param: port_name }
      network: { get_param: network_name }
      fixed_ips: [{ 'ip_address': { get_param: app_eth0_ip}, 'subnet': { get_param: subnet_name} }]
      port_security_enabled: false

  Dummy_App:
    type: OS::Nova::Server
    properties:
      name: Dummy_App
      image: { get_param: image_name }
      config_drive: true
      flavor: { get_param: flavor_name }
# keypair_name: { get_param: keypair_name }
      networks:
         - {network: { get_param: network_name }}
         - {network: { get_param: network_name2 }}

      user_data:
        str_replace:
          template: |
           properties:
            - hostname:Dummy_App
            - ip-info:$eth0_ip/$mask

          params:
            $eth0_ip:      { get_param: app_eth0_ip }
            $mask:      { get_param: app_mask }
       

